/* METRICS */
INSERT INTO metric (METRIC_ID, METRIC_CODE, MAX_VALUE, MIN_VALUE, MINIMUM_SIGN, OBJETIVE_SIGN, OPTIM_SIGN, METRIC_UNIT, UNSATISFACTORY_SIGN) VALUES (1, 'QA_MONITORS', 10000, 0, '>=', '>=', '>=', 'Puntos', '<');
INSERT INTO metric (METRIC_ID, METRIC_CODE, MAX_VALUE, MIN_VALUE, MINIMUM_SIGN, OBJETIVE_SIGN, OPTIM_SIGN, METRIC_UNIT, UNSATISFACTORY_SIGN) VALUES (2, 'QA_PTS_ACHIEVED', 5000, 0, '>=', '>=', '>=', 'Puntos', '<');
INSERT INTO metric (METRIC_ID, METRIC_CODE, MAX_VALUE, MIN_VALUE, MINIMUM_SIGN, OBJETIVE_SIGN, OPTIM_SIGN, METRIC_UNIT, UNSATISFACTORY_SIGN) VALUES (3, 'QA_PTS_POSSIBLE', 5000, 0, '>=', '>=', '>=', 'Puntos', '<');
INSERT INTO metric (METRIC_ID, METRIC_CODE, MAX_VALUE, MIN_VALUE, MINIMUM_SIGN, OBJETIVE_SIGN, OPTIM_SIGN, METRIC_UNIT, UNSATISFACTORY_SIGN) VALUES (4, 'AVAIL_TM', 5000, 0, '>=', '>=', '>=', 'Minutos', '<');
INSERT INTO metric (METRIC_ID, METRIC_CODE, MAX_VALUE, MIN_VALUE, MINIMUM_SIGN, OBJETIVE_SIGN, OPTIM_SIGN, METRIC_UNIT, UNSATISFACTORY_SIGN) VALUES (5, 'AVG_TALK_TM', 86400, 0, '>=', '>=', '>=', 'Segundos/Llamada', '<');
INSERT INTO metric (METRIC_ID, METRIC_CODE, MAX_VALUE, MIN_VALUE, MINIMUM_SIGN, OBJETIVE_SIGN, OPTIM_SIGN, METRIC_UNIT, UNSATISFACTORY_SIGN) VALUES (6, 'AUX_TM', 3960, 0, '<=', '<=', '<=', 'Minutos', '>');
INSERT INTO metric (METRIC_ID, METRIC_CODE, MAX_VALUE, MIN_VALUE, MINIMUM_SIGN, OBJETIVE_SIGN, OPTIM_SIGN, METRIC_UNIT, UNSATISFACTORY_SIGN) VALUES (7, 'NCH', 10000, 0, '>=', '>=', '>=', 'Llamadas', '<');
INSERT INTO metric (METRIC_ID, METRIC_CODE, MAX_VALUE, MIN_VALUE, MINIMUM_SIGN, OBJETIVE_SIGN, OPTIM_SIGN, METRIC_UNIT, UNSATISFACTORY_SIGN) VALUES (8, 'TPCT', 100, 0, '<=', '<=', '<=', '%', '>');

/* CAMPAIGNS */
INSERT INTO campaign (CAMPAIGN_ID, CAMPAIGN_NAME, CAMPAIGN_DESCRIPTION, START_DATE, END_DATE, TYPE, OPTIM_VALUE, OBJETIVE_VALUE, MINIMUM_VALUE) VALUES (1, 'COCA-COLA', 'CAMPAÑA COCA ZERO', '2010-01-01', '2010-12-31', 'INBOUND', 4, 3, 2);

/* SUPERVISORS */
INSERT INTO supervisor (SUPERVISOR_ID, DNI, NAME, SURNAME, CAMPAIGN_ID) VALUES (121, 30321382, 'Pepe', 'Argento', 1);

/* CAMPAIGN_METRIC */
INSERT INTO campaign_metric (CAMPAIGN_ID, METRIC_ID, OPTIM, OBJECTIVE, MINIMUM, UNSATISFACTORY) VALUES (1, 1, 500, 400, 300, 200);
INSERT INTO campaign_metric (CAMPAIGN_ID, METRIC_ID, OPTIM, OBJECTIVE, MINIMUM, UNSATISFACTORY) VALUES (1, 2, 400, 350, 200, 100);
INSERT INTO campaign_metric (CAMPAIGN_ID, METRIC_ID, OPTIM, OBJECTIVE, MINIMUM, UNSATISFACTORY) VALUES (1, 3, 500, 275, 200, 150);